@mailbox_defaults = english

namespace inbox {
  inbox = yes

  mailbox Drafts {
    special_use = \Drafts
  }

  mailbox Junk {
    auto = subscribe
    special_use = \Junk

    sieve_script learn-spam {
      cause = COPY
      driver = file
      path = /etc/dovecot/antispam/sieve/learn-as-spam.sieve
      type = before
    }
  }

  mailbox Trash {
    special_use = \Trash
  }

  mailbox Sent {
    special_use = \Sent
  }

  mailbox "Sent Messages" {
    special_use = \Sent
  }

  mailbox "*" {
    sieve_script learn-ham {
    }
  }

  imapsieve_from Junk {
    sieve_script learn-ham {
      cause = COPY
      driver = file
      path = /etc/dovecot/antispam/sieve/learn-as-ham.sieve
      type = before
    }
  }
}
